name: Build and deploy to production
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
defaults:
  run:
    shell: bash
jobs:
  build:
    if: "${{ startsWith(github.event.head_commit.message, 'ci: [bot]')}}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Cache restore
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{ github.workspace }}/.hugo_cache
          key: hugo-${{ github.run_id }}
          restore-keys:
            hugo-

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (with layer cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: hugo-site:ci
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build the site
        run: docker compose --profile build-production run --rm build-production
        env:
          BASE_URL: ${{ steps.pages.outputs.base_url }}

      - name: Cache save
        id: cache-save
        uses: actions/cache/save@v5
        with:
          path: ${{ github.workspace }}/.hugo_cache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4